language: python
python:
  - "2.6"
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
install:
  - "pip install pelican coveralls"
  - "pip install ."
script: nosetests --with-coverage --cover-package=extended_sitemap extended_sitemap
after_success:
  coveralls